// <auto-generated />
namespace Empty.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Email_added_to_EmployeeModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Email_added_to_EmployeeModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202106212131061_Email_added_to_EmployeeModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
