// <auto-generated />
namespace Empty.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class skill_employee_relation_removed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(skill_employee_relation_removed));
        
        string IMigrationMetadata.Id
        {
            get { return "202106222026139_skill_employee_relation_removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
