// <auto-generated />
namespace Empty.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Skill_Employee_relation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Skill_Employee_relation));
        
        string IMigrationMetadata.Id
        {
            get { return "202106221913067_Skill_Employee_relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
